// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// reglinC
List reglinC(NumericVector x, NumericVector y);
RcppExport SEXP _MyFirstRPackage_reglinC(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(reglinC(x, y));
    return rcpp_result_gen;
END_RCPP
}
// reglinpvalueC
double reglinpvalueC(NumericVector x, NumericVector y, int M);
RcppExport SEXP _MyFirstRPackage_reglinpvalueC(SEXP xSEXP, SEXP ySEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(reglinpvalueC(x, y, M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MyFirstRPackage_reglinC", (DL_FUNC) &_MyFirstRPackage_reglinC, 2},
    {"_MyFirstRPackage_reglinpvalueC", (DL_FUNC) &_MyFirstRPackage_reglinpvalueC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MyFirstRPackage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
