# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reglinC <- function(x, y) {
    .Call('_MyFirstRPackage_reglinC', PACKAGE = 'MyFirstRPackage', x, y)
}

reglinpvalueC <- function(x, y, M = 10000L) {
    .Call('_MyFirstRPackage_reglinpvalueC', PACKAGE = 'MyFirstRPackage', x, y, M)
}

